site_name: Wiki-Ludique UPlanet
site_description: Réenchantons la coopération – Créez, explorez, enrichissez.
site_url: https://papiche.github.io/
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime
  font:
    text: Fira Sans
    code: Fira Mono
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.action.edit
nav:
  - Accueil: index.md
  - Règles:
      - Règles de base: regles/base.md
      - Règles alternatives: regles/alternatives.md
  - UPlanets:
      - Exemple: uplanets/exemple-uplanet.md
      - Modèle de fiche: uplanets/modele-fiche.md
  - Scénarios:
      - La Révolte des Nodes: scenarios/la-revolte-des-nodes.md
      - Créer un scénario: scenarios/modele-scenario.md
  - Personnages:
      - Zenitha: personnages/ambassadrice-zenitha.md
      - Fiche modèle: personnages/fiche-modele.md
  - Ressources: ressources/outils.md
  - Communauté:
      - Gouvernance: communaute/gouvernance.md
      - Hall of Fame: communaute/hall-of-fame.md
  - Développement:
      - Guide du développeur: docs/index.md
      - Référence API: docs/api-reference.md
      - Guide de démarrage rapide: docs/quickstart.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/papiche/papiche.github.io
    - icon: fontawesome/solid/globe
      link: https://astroport.one
repo_url: https://github.com/papiche/papiche.github.io
edit_uri: edit/main/docs/
plugins:
  - search
